spring.application.name=LongDistanceBus
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/longdistancebus?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=change_this_to_a_really_long_random_secret_at_least_32_chars

# Hi?n l?i chi ti?t (gi? khi ?ang debug)
server.error.include-message=ALWAYS
server.error.include-binding-errors=ALWAYS
server.error.include-stacktrace=ALWAYS

# Logging (có th? h? xu?ng INFO sau khi xong)
logging.level.root=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false
